In [1]:
#------------------------------------------------------------------------------
# ECEN 5773 Developing the Industrial Internet of Things
# University of Colorado, Boulder
# College of Engineering and Applied Science.
# Instructor: Dave Sluiter
# 
# Praticing Python assignment.
#
# Using the python_training notebook as a guide, complete the following cells
# in this notebook. 
#
# Run all of the cells and save the notebook.
#
# To turn in to Canvas: The saved practicing_python.ipynb file.
#------------------------------------------------------------------------------

#------------------------------------------
# 1 Basic Data Types
#------------------------------------------

# assign the integer value of 25 to a variable and print the variable.
my_int = 25
print(my_int)

# assign the floating point value of 2.716 to a variable and print the variable.
my_float = 2.716
print(my_float)

# assign a string consisting of your first and last names to a variable and print the variable.
my_name = "Armando Pinales"
print(my_name)



25
2.716
Armando Pinales


In [9]:
#-----------------------------------------------------
# 2 Lists (arrays) and dictionaries (associative arrays)
#-----------------------------------------------------

# create a list with the names of 3 friends and print each element in the list
my_friends = ["Alice", "Bob", "Eve"]

for friend in my_friends:
    print(friend)

# create a dictionary that contains keys that are the names of your 3 favorite books,
# with the values being 1 for your 1st favorite, 2 for your second favorite, and 3
# for your 3rd favorite. print the key and the value of your 1st favorite book.

my_dict = {
    "harry potter": 3,
    "dune": 2,
    "A Series of Unfortunate Events": 1,
}

for k, v in my_dict.items():
    if v == 1:
        print(f"Book: {k}\tRating: {v}")



Alice
Bob
Eve
Book: A Series of Unfortunate Events	Rating: 1


In [11]:
#------------------------------------------
# 3 If/else and for loops, iterators and while loops
#------------------------------------------

# create a for loop that prints the values 10 to 100, stepping by 10 each time
# through the loop.
for num in range(10, 110, 10):
    print(num)




10
20
30
40
50
60
70
80
90
100


In [15]:
#------------------------------------------
# 4 Functions
#------------------------------------------

# create a function that accepts 2 inputs, multiplies them together, and
# then adds 5, and returns that value to the caller. Call that function
# with 2 parameters and print the result.

def my_func(val1: int, val2: int):
    return ((val1 * val2) + 5)

print(my_func(3,3))

14


In [19]:
#------------------------------------------
# 5 Numpy library
# numpy implements matrix construction and operations
#
# See: https://numpy.org/doc/1.21/
#      https://numpy.org/doc/1.21/user/absolute_beginners.html
#
# Both sci-kit learn and tensor flow models can read np arrays.
#
# The np library contains many methods for performing matrix
# operations so you don't have to spend time coding all those
# lower-level details, examples include matrix transpose, 
# and matrix multiplication etc - yay!
#------------------------------------------

import numpy as np  # linear algebra


# create a [3x4] np matrix and a [4x3] np matrix, multiply them together (dot)
# yielding a [3x3]. print the resulting [3x3] matrix values.
matrix_3x4 = np.array( [ [1, 2 ,3 , 4], [5, 6, 7, 8], [9, 10, 11, 12] ] )
matrix_4x3 = np.array( [ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12] ] )

matrix_3x3 = np.dot(matrix_3x4, matrix_4x3)
print(f"Matrix:\n{matrix_3x3}\nShape: {matrix_3x3.shape}")


Matrix:
[[ 70  80  90]
 [158 184 210]
 [246 288 330]]
Shape: (3, 3)


In [23]:
#------------------------------------------
# 6 Pandas library
# Pandas implements a more sophisticated numpy library.
# The library functions much like Excel spreadsheets. Think "np arrays" but with
# column header values and row header values, typically text fields that describe
# the column or the row. Row headers are referred to as "index" values and column headers
# are referred to as "column" values. If you execute len(series_name), you'll get the
# number of rows in the Series. I think of this as the "depth" of the Series.
#
# See docs at: https://pandas.pydata.org/pandas-docs/stable/reference/frame.html
# 
# Key concepts:
#
# First we have a data structure known as a Series. You can think of a Series as a
# column vector of data. They operate much like a dictionary and indexed by the row index "keys".
# The one difference with a series vs. a dictionary is that a Series has to contain element 
# values that are all of the same data type - be aware.
#
# Second, multiple Series can be arranged into a 2-d matrix of Series called a
# DataFrame. A 2-d data frame is a classic Excel Spreadhseet. The default row and
# column header values are numbers that range from 0 to m-1, n-1, where m-1 is the number
# rows and n-1 is the number of columns. Here's the tricky bit that I found, each
# Series (dictionary) in a data frame has to have the same key values, i.e. the same row index
# values. The index and column variables are not static, but can be updated programatically.
# Once the index and column header values have been assigned (or not, i.e. using the
# default values), sorting or otherwise rearranging the rows and columns in a data frame
# does not result in changing the header values. So imagine a data frame:
#
#     A   B   C
# 0   5   6   7
# 1   10  60  30
# 2   50  20  70
#
# And you rearrange (sort) the data frame on column B values, say from largest to smallest,
# you'd get:
#
#     A   B   C
# 1   10  60  30
# 2   50  20  70
# 0   5   6   7
#
# See that those row index values (0, 1, 2) "follow along" with the data.
#
# Tensor flow models can read pandas arrays. I haven't tried sci-kit learn models.
#
#------------------------------------------

# See: https://pythonhow.com/accessing-dataframe-columns-rows-and-cells/

import pandas as pd

# create a data frame with 4 rows with index values 0 to 3, and 4 columns
# with column header values of A, B, C and D. print all the values of the data frame
# including the row index values and the column header values.

# Create data for array
text = "Hi I am a sentance with a length of sixteen words for the pandas data structure"
text_list = text.split(' ')
text_4x4 = np.reshape(text_list, (4, 4))

# generate labels
index_labels = [0, 1, 2, 3]
column_labels = ['A', 'B', 'C', 'D']

# create the data frame
my_dataframe = pd.DataFrame(text_4x4, index_labels, column_labels)
print(my_dataframe)




          A        B      C          D
0        Hi        I     am          a
1  sentance     with      a     length
2        of  sixteen  words        for
3       the   pandas   data  structure
